name: CI
on:
  push: { branches: [ main ], tags: [ 'R*', 'v*', 'r*' ] }
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest httpx
      - name: Start API (background)
        run: |
          uvicorn lemnisiana.orchestrator.app:app --host 127.0.0.1 --port 8000 &
          echo $! > uvicorn.pid
          for i in {1..60}; do curl -fsS http://127.0.0.1:8000/health && break || sleep 0.25; done
      - name: Run tests
        env: { PYTHONPATH: ${{ github.workspace }} }
        run: pytest -q
      - name: Stop API
        if: always()
        run: kill $(cat uvicorn.pid) || true
